services:
  postgres:
    image: postgres:15
    container_name: viskatera_postgres
    environment:
      POSTGRES_DB: viskatera_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - viskatera_network

  adminer:
    image: adminer
    container_name: viskatera_adminer
    ports:
      - "8081:8080"
    networks:
      - viskatera_network
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: viskatera_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - viskatera_network

volumes:
  postgres_data:
  rabbitmq_data:
networks:
  viskatera_network:
    driver: bridge
