services:
  postgres:
    image: postgres:15
    container_name: viskatera_postgres
    environment:
      POSTGRES_DB: viskatera_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - viskatera_network

  adminer:
    image: adminer
    container_name: viskatera_adminer
    ports:
      - "8081:8080"
    networks:
      - viskatera_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  viskatera_network:
    driver: bridge
